name: Check executable permissions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-deploy-permissions:
    name: Ensure deploy.sh is executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if deploy.sh is executable
        run: |
          if [ ! -x ./deploy.sh ]; then
            echo "❌ ERROR: deploy.sh is not executable (missing +x)."
            exit 1
          else
            echo "✅ deploy.sh has correct permissions."
          fi
