name: ✅ Validate deploy.sh executable permission

on:
  push:
    branches: [main]

jobs:
  check-exec:
    name: Check if deploy.sh is executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure deploy.sh is executable
        run: |
          if [ ! -x ./deploy.sh ]; then
            echo "❌ deploy.sh is not executable."
            exit 1
          else
            echo "✅ deploy.sh has +x. All good."
          fi
